modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/Boethie/Genesis/issues"

[[mods]]
modId="genesis"
version="${file.jarVersion}"
displayName="Genesis"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Boethie/Genesis" #change to curse page after release
#logoFile="examplemod.png" #add logo
#credits="" #add credits
#authors="" #add author list
#description='''
# description goes here
#'''
[[dependencies.genesis]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.genesis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"